### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by projetmbc** [nickdelgrosso/helptranslator#1]
Hello.

I have tried your so-good-idea project on one of my project but this gives me the following error message. You can install `mistool` via `pip`.

```
>>> import helptranslator
>>> helptranslator.set_help_lang('french')
>>> from mistool import os_use
>>> help(os_use)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/projetmbc/anaconda3/lib/python3.6/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1858, in __call__
    self.help(request)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1911, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1647, in doc
    output.write(render_doc(thing, title, forceload, plaintext))
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/helptranslator.py", line 22, in write
    translated = translator.translate(string, dest=langcode)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 132, in translate
    data = self._translate(text, dest, src)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 63, in _translate
    data = utils.format_json(r.text)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> import helptranslator
>>> helptranslator.set_help_lang('french')
>>> from mistool import os_use
>>> help(os_use)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/projetmbc/anaconda3/lib/python3.6/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1858, in __call__
    self.help(request)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1911, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/Users/projetmbc/anaconda3/lib/python3.6/pydoc.py", line 1647, in doc
    output.write(render_doc(thing, title, forceload, plaintext))
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/helptranslator.py", line 22, in write
    translated = translator.translate(string, dest=langcode)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 132, in translate
    data = self._translate(text, dest, src)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 63, in _translate
    data = utils.format_json(r.text)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/Users/projetmbc/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/projetmbc/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nickdelgrosso** [comment]
Thank you for your feedback!  After some investigation, I found that this error comes up if google translate receives more than 5000 characters at a time, and the module documentation sent in this example if much longer than that.  I've solved this issue so that Google doesn't receive too much data, additionally adding a cache to reduce network IO on repeated calls.  

Fixed on commit: 44f7ae402f95136d24deb66e90a5e0aea5db9238

installing the latest version should remove this problem.
